services:
  db: 
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: fastapi-container
    depends_on:
      - db
    ports:
      -  "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/mydatabase
    volumes:
      - .:/app
volumes:
  pgdata: